library(tidyverse)
library(reshape2)
library(janitor)
library(readxl)
library(lubridate)
library(data.table)
library(zoo)
library(ggthemes)
library(gghighlight)
library(scales)
library(ggrepel)
library(viridis)

ggsave(filename = "plots/figure1.png", plot = fig1, height = 10, width = 15)
ggsave(filename = "plots/figure2.png", plot = fig2, height = 10, width = 15)
ggsave(filename = "plots/figure3.png", plot = fig3, height = 10, width = 15)
ggsave(filename = "plots/figure4.png", plot = fig4, height = 10, width = 15)
